services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Monta el script y el dump en la carpeta que el entrypoint ejecuta
      - ./01-restore.sh:/docker-entrypoint-initdb.d/01-restore.sh:ro
      - ./backup.dump:/docker-entrypoint-initdb.d/backup.dump:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
